### ISSUE TITLE
io_uring implementieren

### ISSUE THREAD

**Issue by rrcomtech** [hyrise-mp-22-23/hyrise#17]
Implementation of **Read & Write** Benchmarks.

**Comment by rrcomtech** [comment]
Implementing io_uring is very difficult! 
Therefore, we will advance to a different topic as long as there is no further evidence on the advantages of io_uring.

**Comment by phoeinx** [comment]
Seems sensible - could you perhaps document the main challenges/issues here shortly so we have them at hand? 🙏

**Comment by SanJSp** [comment]
> Seems sensible - could you perhaps document the main challenges/issues here shortly so we have them at hand?
@rrcomtech

**Comment by rrcomtech** [comment]
Please see [Miro](https://miro.com/app/board/uXjVPEbxkpM=/?moveToWidget=3458764539781952931&cot=14).
