### ISSUE TITLE
[Storage Infrastructure] Define a file format

### ISSUE THREAD

**Issue by rrcomtech** [hyrise-mp-22-23/hyrise#79]
- [x] Store a `storage format version id`
    - start at beginning of file
    - whenever format version changes, increment id 
- [x] each file should contain 50 chunks
- [x] self-contained segments and chunks
- [x] each chunk should have a header
    - offsets allow loading arbitrary chunks
    - suggested header: `int version_id, std::vector<int>(50) chunk_ids, std::vector<int>(50) chunk_offset_end` (see [MP Tasks](https://docs.google.com/document/d/1GT8DwQDuZZDbTf_AozdiaPtM8iOD9Q-IGDLCj74wdHE/edit))

Please use existing work from #56 and #59.

**Comment by Bouncner** [comment]
Any news here?

**Comment by tjjordan** [comment]
We are working on it.
Work takes place on the branches `define_file_format` and `file_format_refactored`.

**Comment by tjjordan** [comment]
For a slightly different approach have a look an the branch `file_format_refactored`.
But note that it is also very wip.
