### ISSUE TITLE
[Storage Manager] Memory-Mapped Storage Manager Mode

### ISSUE THREAD

**Issue by rrcomtech** [hyrise-mp-22-23/hyrise#80]
The storage manager should be able to run in a memory-mapped mode.

### Storage Manager Responsibility

The storage manager takes over the responsibility of storing data. Previously, this was given to the segments, but not anymore. 

Data from the storage manager should be written to `./storage`.

- [ ]  Users / Benchmarks can provide a different path than `./storage`. 

### Data Management

- [ ] Define how a storage manager will manage different files and segments.
- [ ] Define a mechanism, when data is allowed to be read and when not.

### Loading Data 

- [ ]  On Startup ("when the storage manager is initiated"), the storage manager should load data from `./$db_path/storage.json`. **TODO: What does "listed" mean? Is the data or the location listed?**
- [ ] For each file, the storage manager holds a mmap pointer.
- [ ] _For mmap segments, the storage manager holds a unique_ptr per mapped file. Segments are created from this file by calling the segment's constructor with a pointer to the segment’s data + the size of this data (the storage manager does not need to know how to handle segment data)._ **TODO: I have no idea what this paragraph tries to say.**

**Comment by Bouncner** [comment]
@rrcomtech , are some points still unclear? Or did the Google Doc discussion clear up everything?

**Comment by rrcomtech** [comment]
@Bouncner Currently not, thank you! :)

**Comment by Bouncner** [comment]
What's the status on the storage manager?

**Comment by rrcomtech** [comment]
We are transferring methods from the playground to the storage manager. This is still WIP.
