### ISSUE TITLE
[Storage Manager] Implement a DRAM-Resident Mode

### ISSUE THREAD

**Issue by rrcomtech** [hyrise-mp-22-23/hyrise#81]
While there is the focus on a memory mapped mode, there should be a DRAM-resident mode, which does not change Hyrise's behavior.

**Comment by Bouncner** [comment]
To be precise here: there will probably be changes to segments in case there is a DRAM-resident mode and a MMAP-mode. But those changes should not touch anything outside of the `storage/` directory.

**Comment by rrcomtech** [comment]
Moved to Future Work.
