### ISSUE TITLE
[Storage IO] Write Chunks to Disc after they are finalized

### ISSUE THREAD

**Issue by rrcomtech** [hyrise-mp-22-23/hyrise#82]
Chunks now have one of two default encodings:

- `FixedStringDictionary`: For strings
- `Dictionary`: For numeric Data Types

- [ ] As soon, as a chunk is finalized, forward it to the storage manager (look at the `finalize` method in `src/lib/storage/chunk.cpp`).
- [ ] Write the chunk to disc (requires #79). 
- [ ] Ensure there is no parallel write to a file. For that, one could use mutexes.
- [ ] Implement a mechanism to write a segments "raw data" to a file.

**Comment by Bouncner** [comment]
Who is responsible for this task?
What is the status here?

**Comment by rrcomtech** [comment]
Closing, since no further contribution.
