### ISSUE TITLE
[Dictionary] Change Internal Data Structure to use std::span

### ISSUE THREAD

**Issue by rrcomtech** [hyrise-mp-22-23/hyrise#83]
Change the dictionary’s internal structure to use std::span (first, store the data in the segment, once it runs; move to storage manager).

**Comment by Bouncner** [comment]
I would recommend adapting the current dictionary segment. Adding new segments types can be a little bit of a pain (and adds compile time).

What can be done here:
- continue to use the std::vector INTERNALLY for the first steps
- use std::spans that are defined on top of vectors.data()
- find all cases, where the vectors are accesses and rewrite to spans
  - there is a function that gets the dictionary, that should be easy to rewrite
  - there are the iterables (here pass 99% of the accesses to segments through) which need a few adaptions

Once we know if that works (there are always problems coming up) we can get rid of the std::vectors and store data in a "chunk of bytes".

**Comment by Bouncner** [comment]
Any news here?

**Comment by phoeinx** [comment]
Have not started yet, as my working days this week are Friday and Sunday. Will start working on it after lunch and perhaps have some updates this evening.

**Comment by Bouncner** [comment]
Any news here?

**Comment by phoeinx** [comment]
@tjjordan  and me will start on implementing this now

**Comment by rrcomtech** [comment]
Is implemented.
