### ISSUE TITLE
Diskussion: Anforderungen an den Storage Manager

### ISSUE THREAD

**Issue by SanJSp** [hyrise-mp-22-23/hyrise#96]
In Deutsch, um nicht zusätzliche Komplexität aufzutragen.

Wir hatten folgenden Vorschlag ins Weekly mitgebracht:
![image](https://user-images.githubusercontent.com/38314662/217017946-4db9b3bf-fb9a-4088-8b12-a2cbcaf8e636.png)
![image](https://user-images.githubusercontent.com/38314662/217018137-ee9356dc-d5b0-4cae-9f0f-1e1a350ddbd7.png)

Dieser Vorschlag zielt darauf ab, den Storage Manager die maps zu erstellen und verwalten zu lassen und nur nach dem finalizen der Chunks die Segmente der Chunks von DictSegments zu SpanDictSegments auszutauschen. 

Dabei ist uns aufgefallen, dass wir nicht ganz sicher bezüglich der Anforderungen und Aufgaben des Storage Managers sind. 

Folgende Fragen haben wir diskutiert und wollen sie hier erneut dokumentieren/ansprechen:
1. Was gibt der Storage Manager nach dem Mappen zurück? → Idee: Sharedpointer auf SpanSegments
2. Wer hat Ownership auf den Pointer des mmapten Bereichs? → Idee: Storage Manager
3. Welche Rolle spielt der Storage Manager überhaupt? Ist es ein Buffer Manager? Ein Interface auf mmap als Buffer Manager?
4. Welche Datenstruktur verwenden wir, um eine Referenz von Chunk auf maps zu verwalten?
5. Was passiert, wenn wir eine Tabelle löschen? → Primär ausgelassen, aber langfristig doch wichtig
6. Wer tauscht die DictSegments zu SpanDictSegments?
7.  Was für Anforderungen gibt es allgemein an den Storage Manager, welche Runtime Informationen bzgl. Speicherort von Segmentdaten sollen zur Verfügung stehen etc.

Die Fragen dienen dazu, die Punkte wieder im Kopf aufkommen zulassen, weitere Themen/Zuständigkeiten dürfen gerne ergänzt werden 😊

**Comment by mweisgut** [comment]
Gedanken dazu:
`create_map` als Funktion des StorageManagers klingt sehr mmap-spezifisch. Ggf. hilft es uns, die Erstellung eines Segmentes von der Erstellung einer Memory-Region, dessen Adressbereich wir für die Erstellung eines Segments genutzt werden kann, zu unterscheiden. Der StorageManager könnte z.B. ein oder mehrere MemoryRegions verwalten. Diese MemoryRegions könnten verschiedene Eigenschaften haben, so könnte es einen MemoryRegion-Typen geben, der via mmap file-mapped ist und somit Seiten von dem Betriebssystem verwaltet werden. Eine solche MemoryRegion wird dann für eine Menge von Segmenten genutzt, d.h. die Daten von Segment liegen in unterschiedlichen Teil-Bereichen der MemoryRegion.

Bzgl. Kardinalitäten würden
- die Daten einer Tabelle auf mehreren MemoryRegions verteilt sein
- eine MemoryRegion die Daten mehrere Segmente enthalten

Bzlg. 2. könnte man also eine MemoryRegion-Klasse (o.ä.) erstellen, die den Pointer verwaltet. Zunächst könnte der StorageManager solche MemoryRegions verwalten, was man bei Bedarf natürlich anpassen könnte, sofern wir zu einem Zeitpunkt meinen, der StorageManager sei nicht die richtige Stelle dafür.

4. Chunk auf maps heißt Chunk auf Memory-Regionen?

6. `Chunk::replace_segment` kann dafür genutzt werden. Ggf. zunächst als Teil von `Chunk::finalize()`, d.h. in dieser Funktion würde dann über die Segmente iteriert werden, das `SpanDictSegment` erstellt werden (sofern es zwei Typen geben soll) und das alte Segment mit `replace_segment` ersetzt werden.

7. Offene Fragen waren zudem
- wann wird munmap aufgerufen? Wie stellen wir sicher, das munmap nur für Memory-Regionen aufgerufen wird, dessen Adressbereich für keine Segmente/Datenstrukturen mehr verwendet wird? Vorschlag: Eine Art Reference-Counting pro Memory-Region?
- wenn wir für die Query-Ausführung speichermediumsabhängige Optimierungen durchführen wollen, wäre es hilfreich, pro Segment zu wissen, auf welche Art von Speicher dieses liegt.

**Comment by klauck** [comment]
Ich würde die erste Version so einfach wie möglich halten und annehmen, dass erstmal alle finalisierten Chunks auf Festplatte liegen und gemappt sind.
zu 1) irgendetwas was funktioniert ;)
zu 2) ja
zu 3) Der Storagemanager verwaltet die gemappten Bereiche. (Das OS ist der Buffermanager)
zu 4) irgendetwas was funktioniert ;)  (verstehe nicht 100%ig was ihr meint, aber eine Hash-Map / Dictionary ist meist recht flexibel für den Start)
zu 5) Welches Problem seht ihr bei gelöschten Tabellen. (Wir müssen den Bereich unmappen und die Tabelle aus dem Storagemanger entfernen.)
zu 6) Ich denke der Storagemanger macht das pro Chunk (oder Segment). Finde den Ablauf in euerem Sequenzdiagramm dazu erstmal gut
zu 7) Ich denke, erstmal map-only für finalisierte Chunks.

**Comment by Bouncner** [comment]
Generell würde ich nicht dazu raten über Regions nachzudenken, wenn wir keinen Use Case dafür haben. @mweisgut Kannst  du ggf. genauer erläutern, warum wir uns Regions angucken sollten?
Wie Stefan sagt, wird der meiste Speicher durch das memory-mapping vom OS verwaltet werden. Für die Fälle, dass wir auf DRAM-Segmente gucken, würde ich es extreeeem simple halten und sagen, dass der StorageManager eine einmethodige-Klasse namens "Speicherverwalter" anfragt und diese einfach nur einen unique_ptr auf Speicher herausgibt, in denen dann z.B. die memory-mapped Segment kopiert werden können. Wirklich einfach zum jetzigen Zeitpunkt.

Stefan hat eigentlich das meiste gesagt. Der Vollständigkeit halber:
1.) Wer ruft denn was auf, dass der StorageManager etwas zurückgeben muss? Ich komme gerade nur auf `void`, da ich erwarten würde, dass es einfach eine Methode `load_database()` gibt oder so ähnlich.
2.) ja
3.) Der StorageManager verwaltet mmap als auch die Pointer auf die "stored segments" when diese im DRAM gelagert sind. Er ist die Anlaufstelle für alles, was in der Datenbank persistent ist (also die Tabellen). In meinen Augen ist daher die Antwort: sowohl halten der mmaps (als auch später halten der Pointer auf die Segment-Daten, wenn diese im DRAM liegen).
4.) Kommt drauf an, was der StorageManager intern so speichert. Pro Chunk könnte das ein Offset sein in die Liste der mmap's des StorageManagers. Aber die Frage kommt zu früh. Wir brauchen erst alle Anforderungen.
5.) Die Tabelle wird gelöscht. :D D.h. aus dem StorageManager entfernt. Wenn man lustig ist, kann man mmap's entfernen, die keinerlei andere Daten mehr halten. Oder gar die Files löschen. Out of scope aktuell IMO.
6.) Wie Marcel sagt, `replace_segment`.

Zu den Anforderungen:
- ich möchte pro Chunk gern wissen, auf welche Art es gespeichert ist (das könnte aktuell eine `enum class` sein den Einträgen `memory-mapped` und `DRAM`). Also es reicht die Eigenschaft im Chunk und das "sichere" Schreiben dieser Eigenschaft, sobald umgezogen wird.

So wirklich harte Anforderungen fallen mir gerade kaum ein. Die meisten ergeben sich, sobald am StorageManager geschraubt wird.

**Comment by mweisgut** [comment]
>Generell würde ich nicht dazu raten über Regions nachzudenken, wenn wir keinen Use Case dafür haben. @mweisgut Kannst du ggf. genauer erläutern, warum wir uns Regions angucken sollten?

Sobald wir einen `mmap`-Aufruf nutzen, arbeiten wir mit einer Memory-Region / einem virtuellen Adressbereich.

> sowohl halten der mmaps (als auch später halten der Pointer auf die Segment-Daten, wenn diese im DRAM liegen).

Sind mit `mmaps` Startadressen auf die gemappten Memory-Regionen gemeint?
Anstatt `mmap` im StorageManager aufzurufen, Startadressen im StorageManager zu verwalten und mit `munmap` das Mapping des gegebenen Adressbereiches zu löschen, ist die Idee, Funktionalität in einer MemoryRegion-Klasse (o.ä.) zu kapseln. D.h. das Erstellen des Mappings (`mmap`) könnte dann z.B. im Konstruktor und das Löschen des Mappings (`munmap`) im Dekonstruktor aufgerufen werden. Somit müssten wir nicht im StorageManager selbst mit `mmap` / `munmap` arbeiten. Zudem benötigen wir Informationen darüber, ob noch irgendwelche SpanSegmente Teilbereiche eines gemappten Adressbereiches nutzen. In dem Fall können wir `munmap` nicht aufrufen. Solche Informationen könnten auch als Statistiken in einem MemoryRegion-Objekt (o.ä.) gehalten werden. 

Zwingend notwendig ist eine solche Klasse natürlich nicht - wie mit jeder Klasse. Sie würde jedoch Funktionalität und ggf. State kapseln.

>Generell würde ich nicht dazu raten über Regions nachzudenken

Aber auch, wenn wir eine MemoryRegion-Klasse nicht einführen wollen, würde ich dennoch meinen, unbedingt über Memory-Regionen nachzudenken, wenn wir mit `mmap` arbeiten.

**Comment by Bouncner** [comment]
Ahhh, got you.

Verdammt. Ich lese den Kommentar erst jetzt und wir hatten heute drüber gesprochen. Ich finde den Namen `MemoryRegion` noch verwirrend, weil ich nicht verstehe, was das direkt mit `mmap` zu tun hat bzw. was es von einer normalen Allocation unterscheidet.

Aber das ganze zu kapseln klingt definitiv sinnvoll. Vor allem, dass wir damit die Zuordnung file-mapping <-> Segment kapseln, finde ich gut.

**Comment by rrcomtech** [comment]
Closed since we advanced.
